id: ADA5B3BED
base_file: fC20A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:16:28.878518
  last_modified_at: 2022-05-30 18:16:28.878528
